language: cpp
sudo: true

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
      - compiler: gcc
        addons:
         apt:
           packages: &precise_latest_boost_packages
             - gcc-4.8
             - g++-4.8
             #- gcov-4.9
             - clang-3.7
             - valgrind
             # Misc
             - python-yaml
             - lcov
             # - libopencv-dev
             # - libgtest-dev
           sources: &precise_latest_boost_sources
             - ubuntu-toolchain-r-test
             - llvm-toolchain-precise-3.7
        env: COMPILER=g++-6
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - sudo pip install codecov
    
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

    - sudo apt-get install libgtest-dev
    - cmake -DCMAKE_BUILD_TYPE=Release /usr/src/gtest
    - cmake --build .
    - sudo mv lib*.a /usr/lib

    # - apt-get install cmake # install cmake
    # - cd /usr/src/gtest
    # - cmake CMakeLists.txt
    # - make
    # - cp *.a /usr/lib
    # - ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
    # - ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a


    # - git clone https://github.com/google/googletest.git
    # - cd googletest
    # - mkdir build && cd build
    # - cmake .. -DGTEST_LANG_CXX17=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_GMOCK=OFF -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
    # - make
    # - make install
    # - ldconfig


    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - cmake --version

# before_script:
#     - cd /usr/src/googletest
#     - cmake .
#     - cmake --build . --target install

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - make test


after_success:
    # - codecov -t c376990f-2ad6-4f7b-bbdb-5378a52e295c -X gcov