language: cpp
compiler: gcc

dist: focal
addons:
  sonarcloud:
    organization: "ilyajob05"
    token:
      secure: "nALVyOYoJpb1IwWx28OMVGv9TJblhcvX0lxe/uD64na2+mXXflnWAOCJwaObWGVSqdiOkWGcrc/cjrVeuo0EoHZ/IiM8h0wFDPf2Pq134N/BsXdlus87//u+oQulkozS4KGyZuAlFmSyQkQC5cxmRT6PK3vzoJaspIUcTeLagQbqH6sAgZTLuQ7IiGnscgErR3yOZh8Gs+PydctuyCCEY9dFq/JPTfqEjUtshdnpVF9OzJrL35a44zfGaLjSha9le8Ee63mjxIGVT/5abCLn0YMp8ROSpI3w/66X8pw4IbBJvw40/xwlefCLrvfzkVX6lyYiMYZLFSXZr8zCJYQDm7OaQ0U/PhSklDfiYnK0WrZ4E84NxpD1wDpxZrq/SWxviOGjQev2udVFj/P1/Edde3x/2zsDo0XBKr7WeL+LThvxxlYWWpC1wLHijtp/yXTJpGqNXPM6U7LWlttTJChNkKZiAou733p4+3f17Boqfbb12CDj/I2F7aDhdmq/2evp9wYdhPVZBWx3mXWGdyuasyskGM6u0T2A1Sg7MDAygaNdI/wK0QDej6mLXWc3d9zUkSvM9oTISLZQsu/Llx9WvmkZd0CpBTxYDXkYBHuraUfmDZL99I19i27ht5TIKOTGKsc76clYiwh5PYXlJDGTrLjKnmJGVlqFmU94WHB3SM0="
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - valgrind

before_install:
    # Combine global build options with OS/compiler-dependent options

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
#    - sudo pip install codecov
    - sudo apt-get install libgtest-dev
    - cmake -DCMAKE_BUILD_TYPE=Release /usr/src/gtest
    - cmake --build .
    - sudo mv lib/lib*.a /usr/lib
    - rm CMakeCache.txt cmake_install.cmake Makefile
    - rm -rf CMakeFiles
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - cmake --version

# before_script:

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=DEBUG ..
    - cd ..
    - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/ --target all
    - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
    - cd build
    - make test

after_success:
    - bash <(curl -s https://codecov.io/bash)
