dist: focal
language: cpp
compiler: gcc

cache:
  directories:
  - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "ilyajob05"
    token: "2f8f2781646a1193aee16d9237757956c46bb0f7"
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
#      - g++-7
      - cmake
      - valgrind
      - gcovr
      - python3-pip

env:
  - SONAR=true

before_install:
    # Combine global build options with OS/compiler-dependent options

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
#    - sudo pip install codecov
    - pip3 install --user gcovr
    - sudo apt-get install libgtest-dev
    - cmake -DCMAKE_BUILD_TYPE=Release /usr/src/gtest
    - cmake --build .
    - sudo mv lib/lib*.a /usr/lib
    - rm CMakeCache.txt cmake_install.cmake Makefile
    - rm -rf CMakeFiles
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - cmake --version

# before_script:

script:
    - export CC=gcc-7
    - export CXX=g++-7
    - cmake --version
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=DEBUG ..
    - cd ..
    - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/ --clean-first --target all
    - cd build
    - ctest -C Debug
    - cd ..
    - pwd
    - gcovr --sonarqube coverage.xml
    - cat coverage.xml
    - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

#after_success:
    - bash <(curl -s https://codecov.io/bash)
